# Basic
title: Guanxi Liang's Blog
subtitle: A blog full of fool things
welcome_message: Please click the links blow
description: 
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: About me, description: Resume, url: 'http://localhost:4000/about/'}
    # - {title: Another Button, description: A button, url: 'http://example.com/about.html'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: guanxi-liang
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: garyliang07
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: garyliang86@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
